name: Remote Access with AnyDesk

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: macos-latest

    steps:
      # تنزيل وتثبيت AnyDesk
      - name: Download and Install AnyDesk
        run: |
          echo "Downloading AnyDesk..."
          curl -L -o AnyDesk.dmg https://download.anydesk.com/anydesk.dmg
          hdiutil attach AnyDesk.dmg
          sudo cp -r /Volumes/AnyDesk/AnyDesk.app /Applications
          hdiutil detach /Volumes/AnyDesk
          echo "AnyDesk installed successfully."

      # عرض التعليمات لتشغيل AnyDesk
      - name: Display AnyDesk Info
        run: |
          echo "AnyDesk has been installed. Open the application from /Applications/AnyDesk.app and share your AnyDesk ID for remote access."
