name: Remote Access via VNC on Linux

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: ubuntu-latest

    steps:
      # تثبيت TigerVNC وخادم العرض الافتراضي (Xvfb)
      - name: Install VNC Server
        run: |
          sudo apt update
          sudo apt install -y tigervnc-standalone-server tigervnc-common x11vnc xvfb

      # إعداد خادم العرض الافتراضي
      - name: Start Virtual Display
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1

      # تشغيل خادم VNC
      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1024x768 -localhost no -SecurityTypes None
          echo "VNC Server is running on port 5901"

      # تشغيل Cloudflare Tunnel
      - name: Install Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb
          cloudflared tunnel --url vnc://localhost:5901 > /dev/null &
          sleep 5
          echo "Cloudflare Tunnel URL:"
          cloudflared tunnel list

      # إبقاء الخدمة نشطة
      - name: Keep Server Running
        run: sleep 3600
