name: Ali

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/Ali-157/rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat

      # التقاط لقطة شاشة ورفعها
      - name: Capture Screenshot and Upload
        run: |
          echo "Installing Python and required libraries..."
          curl -s https://bootstrap.pypa.io/get-pip.py | python
          pip install pillow requests
          echo "Capturing screenshot and uploading to GoFile.io..."

          python - <<EOF
import requests
from PIL import ImageGrab

# التقاط لقطة الشاشة
screenshot = ImageGrab.grab()
screenshot.save("screenshot.png")

# رفع الصورة إلى GoFile.io
with open("screenshot.png", "rb") as file:
    response = requests.post(
        'https://api.gofile.io/uploadFile',
        files={'file': ('screenshot.png', file)}
    )

# عرض الرابط في السجلات
data = response.json()
if data['status'] == 'ok':
    print("Screenshot uploaded successfully!")
    print("Download Link:", data['data']['downloadPage'])
else:
    print("Failed to upload screenshot:", data)
EOF
