name: Remote Access to macOS with noVNC

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: macos-latest

    steps:
      # تثبيت Homebrew وتحديثه
      - name: Install Homebrew and Update
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

      # تثبيت TigerVNC وnoVNC
      - name: Install VNC and noVNC
        run: |
          brew install --cask tigervnc-viewer
          brew install noVNC

      # إعداد عرض افتراضي
      - name: Start Virtual Display
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1

      # تشغيل خادم VNC
      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1024x768 -localhost no -SecurityTypes None
          echo "VNC Server is running on port 5901"

      # تشغيل noVNC لتوفير واجهة في المتصفح
      - name: Start noVNC
        run: |
          websockify --web=/usr/local/novnc 6080 localhost:5901 > /dev/null &
          echo "noVNC is running on http://localhost:6080"

      # إبقاء الخدمة نشطة
      - name: Keep Server Running
        run: sleep 3600
