name: Enable RDP and Show IP

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: windows-latest

    steps:
      # 1. تفعيل RDP
      - name: Enable RDP
        run: |
          echo "Enabling Remote Desktop Protocol (RDP)..."
          powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0"
          powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
          echo "RDP enabled successfully."

      # 2. عرض عنوان IP
      - name: Display IP Address
        run: |
          echo "Fetching IP address..."
          for /f "tokens=2 delims=[]" %A in ('ping -4 -n 1 $(hostname)') do echo IP Address: %A
          powershell -Command "(Get-NetIPAddress -AddressFamily IPv4).IPAddress | Out-String"

      # 3. إبقاء الجهاز قيد التشغيل
      - name: Keep Machine Alive
        run: |
          echo "RDP is enabled. Keep this session running for remote access."
          timeout /t 3600
