name: Remote Access to macOS with VNC

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: macos-latest

    steps:
      # تثبيت TigerVNC مباشرة من المصدر الرسمي
      - name: Download and Install TigerVNC
        run: |
          curl -L -o tigervnc-macos.dmg https://downloads.sourceforge.net/project/tigervnc/stable/1.13.0/TigerVNC-1.13.0.dmg
          hdiutil attach tigervnc-macos.dmg
          sudo installer -pkg /Volumes/TigerVNC/TigerVNC-*.pkg -target /
          hdiutil detach /Volumes/TigerVNC
          which vncserver || echo "TigerVNC installation failed!"

      # إعداد شاشة افتراضية
      - name: Start Virtual Display
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1

      # تشغيل خادم VNC
      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1024x768 -localhost no -SecurityTypes None
          echo "VNC Server is running on port 5901"

      # تشغيل Cloudflare Tunnel
      - name: Install and Start Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-amd64.tgz -o cloudflared.tgz
          tar -xvzf cloudflared.tgz
          sudo mv cloudflared /usr/local/bin/cloudflared
          cloudflared tunnel --url vnc://localhost:5901 > /dev/null &
          sleep 5
          echo "Cloudflare Tunnel URL:"
          cloudflared tunnel list

      # إبقاء الخادم قيد التشغيل
      - name: Keep Server Running
        run: sleep 3600
