name: Enable RDP on Windows

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: windows-latest

    steps:
      # تفعيل RDP
      - name: Enable RDP
        run: |
          echo "Enabling Remote Desktop Protocol (RDP)..."
          powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0"
          powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
          echo "RDP enabled successfully."

      # عرض عنوان IP واسم المستخدم
      - name: Display RDP Info
        run: |
          echo "Your RDP connection details:"
          echo "IP Address: $(hostname -I)"
          echo "Username: $(whoami)"
          echo "Use these credentials to connect via Remote Desktop."
