name: Remote Access to macOS with VNC

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: macos-latest

    steps:
      # تثبيت Homebrew يدويًا
      - name: Install Homebrew
        run: |
          echo 'Installing Homebrew manually...'
          mkdir -p /opt/homebrew
          curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /opt/homebrew
          echo 'Adding Homebrew to PATH...'
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew --version

      # تثبيت TigerVNC باستخدام الاسم الصحيح
      - name: Install TigerVNC
        run: |
          brew install tiger-vnc
          brew install --cask tigervnc-viewer
          brew install --cask xquartz

      # إعداد شاشة افتراضية
      - name: Start Virtual Display
        run: |
          Xvfb :1 -screen 0 1024x768x16 &
          export DISPLAY=:1

      # تشغيل خادم VNC
      - name: Start VNC Server
        run: |
          vncserver :1 -geometry 1024x768 -localhost no -SecurityTypes None
          echo "VNC Server is running on port 5901"

      # تشغيل Cloudflare Tunnel
      - name: Install and Start Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-amd64.tgz -o cloudflared.tgz
          tar -xvzf cloudflared.tgz
          sudo mv cloudflared /usr/local/bin/cloudflared
          cloudflared tunnel --url vnc://localhost:5901 > /dev/null &
          sleep 5
          echo "Cloudflare Tunnel URL:"
          cloudflared tunnel list

      # إبقاء الخادم قيد التشغيل
      - name: Keep Server Running
        run: sleep 3600
