name: Remote Access with AnyDesk

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: macos-latest

    steps:
      # تنزيل وتثبيت AnyDesk
      - name: Download and Install AnyDesk
        run: |
          echo "Downloading AnyDesk..."
          curl -L -o AnyDesk.dmg https://download.anydesk.com/anydesk.dmg
          hdiutil attach AnyDesk.dmg
          sudo cp -r /Volumes/AnyDesk/AnyDesk.app /Applications
          hdiutil detach /Volumes/AnyDesk
          echo "AnyDesk installed successfully."

      # تشغيل AnyDesk لأول مرة
      - name: Start AnyDesk
        run: |
          echo "Starting AnyDesk..."
          open -a /Applications/AnyDesk.app
          echo "Please wait while AnyDesk initializes."

      # عرض تعليمات للحصول على رقم AnyDesk
      - name: Display AnyDesk Instructions
        run: |
          echo "To connect to this macOS device:"
          echo "1. Open AnyDesk on macOS from /Applications/AnyDesk.app."
          echo "2. Note the displayed AnyDesk ID and share it with the connecting device."
          echo "3. Use the AnyDesk ID on the remote client to establish the connection."

 - name: Keep Server Running
        run: sleep 3600
